version: "3"

volumes:
  postgtes_volume:

services:
  ncdatabase:
    image: "postgres:latest"
    container_name: "ncdatabase"
    restart: always
    environment:
      - POSTGRES_PASSWORD=ncapp
      - POSTGRES_USER=ncapp
      - POSTGRES_DB=hibernate_db
    ports:
      - "5432:5432"
    volumes:
      - postgtes_volume:/var/lib/postgresql/data

  ncapp:
    environment:
      - QUARKUS_DATASOURCE_USERNAME=ncapp
      - QUARKUS_DATASOURCE_PASSWORD=ncapp
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://ncdatabase:5432/hibernate_db
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    depends_on:
      - ncdatabase