quarkus:
  datasource:
    db-kind: postgresql
    usenrame: ncapp
    password: ncapp
    jdbc:
      url: jdbc:postgresql://localhost:5432/hibernate_db
  hibernate-orm:
    database:
      generation: drop-and-create