quarkus:
  datasource:
    db-kind: postgresql
    username: ncapp
    password: ncapp
    jdbc:
      url: jdbc:postgresql://localhost:5432/hibernate_db
  flyway:
    migrate-at-start: true

"%dev":
  quarkus:
    datasource:
      db-kind: postgresql
      username: ncapp
      password: ncapp
      jdbc:
        url: jdbc:postgresql://localhost:5432/test_db
    flyway:
      migrate-at-start: true
      clean-at-start: true